[Interface]
Address = 10.8.0.2/24
PrivateKey = YOiiH1Gr7FtZLURadmXaKHTXt4/HaPH5f4h++qYsGGM=
DNS = 8.8.8.8, 8.8.4.4
MTU = 1280

[Peer]
PublicKey = ZPcP1XfD8sV4IHxf59Aaw3MRWrFStnMV/Xllgw2UADM=
Endpoint = 192.168.1.102:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
