[Interface]
Address = 10.8.0.2/24
PrivateKey = Phone_Private_Kay
DNS = 8.8.8.8, 8.8.4.4
MTU = 1280

[Peer]
PublicKey = Server_Public_Key
Endpoint = 192.168.1.102:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
